"""Added initial schema

Revision ID: 414cecb4c95e
Revises: 
Create Date: 2024-12-12 23:39:47.826911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414cecb4c95e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('pesel', sa.String(length=11), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=50), nullable=True),
    sa.Column('apartment_number', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pesel')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index('idx_patient_surname', ['surname'], unique=False)

    op.create_table('procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icd9', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('pwd', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('medical_certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('type', sa.INTEGER(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('is_able_to_work', sa.Boolean(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_certificate', schema=None) as batch_op:
        batch_op.create_index('idx_medical_certificate_month', ['month'], unique=False)
        batch_op.create_index('idx_medical_certificate_type', ['type'], unique=False)
        batch_op.create_index('idx_medical_certificate_year', ['year'], unique=False)

    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('color_back', sa.String(), nullable=True),
    sa.Column('color_fore', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('interview', sa.Text(), nullable=True),
    sa.Column('general_info', sa.Text(), nullable=True),
    sa.Column('orl', sa.String(length=100), nullable=True),
    sa.Column('examination', sa.String(), nullable=False),
    sa.Column('recommendations', sa.String(), nullable=False),
    sa.Column('whisper_test', sa.String(), nullable=False),
    sa.Column('nfz_info', sa.String(), nullable=False),
    sa.Column('audiogram_date', sa.Date(), nullable=True),
    sa.Column('examination_date', sa.Date(), nullable=True),
    sa.Column('routine', sa.String(), nullable=True),
    sa.Column('ul_250', sa.Integer(), nullable=True),
    sa.Column('ul_500', sa.Integer(), nullable=True),
    sa.Column('ul_1000', sa.Integer(), nullable=True),
    sa.Column('ul_2000', sa.Integer(), nullable=True),
    sa.Column('ul_3000', sa.Integer(), nullable=True),
    sa.Column('ul_4000', sa.Integer(), nullable=True),
    sa.Column('ul_6000', sa.Integer(), nullable=True),
    sa.Column('ul_8000', sa.Integer(), nullable=True),
    sa.Column('up_250', sa.Integer(), nullable=True),
    sa.Column('up_500', sa.Integer(), nullable=True),
    sa.Column('up_1000', sa.Integer(), nullable=True),
    sa.Column('up_2000', sa.Integer(), nullable=True),
    sa.Column('up_3000', sa.Integer(), nullable=True),
    sa.Column('up_4000', sa.Integer(), nullable=True),
    sa.Column('up_6000', sa.Integer(), nullable=True),
    sa.Column('up_8000', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    op.drop_table('schedule')
    with op.batch_alter_table('medical_certificate', schema=None) as batch_op:
        batch_op.drop_index('idx_medical_certificate_year')
        batch_op.drop_index('idx_medical_certificate_type')
        batch_op.drop_index('idx_medical_certificate_month')

    op.drop_table('medical_certificate')
    op.drop_table('user')
    op.drop_table('procedure')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index('idx_patient_surname')

    op.drop_table('patient')
    # ### end Alembic commands ###
