"""Added not null constraints

Revision ID: 437e7be2d4ec
Revises: d89bc2104f2d
Create Date: 2025-01-16 19:03:57.361461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437e7be2d4ec'
down_revision = 'd89bc2104f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiogram', schema=None) as batch_op:
        batch_op.alter_column('audiogram_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('ul_250',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ul_500',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ul_1000',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ul_2000',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ul_3000',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ul_4000',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ul_6000',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ul_8000',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('up_250',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('up_500',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('up_1000',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('up_2000',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('up_3000',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('up_4000',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('up_6000',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('up_8000',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('medical_certificate', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('info',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('is_able_to_work',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('month',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('apartment_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('procedure', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('date_joined',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('isActive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('diagnosis',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('interview',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('general_info',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('orl',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('examination_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('examination_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('orl',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('general_info',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('interview',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('diagnosis',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('isActive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('date_joined',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('procedure', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('apartment_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('medical_certificate', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('month',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_able_to_work',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('info',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('audiogram', schema=None) as batch_op:
        batch_op.alter_column('up_8000',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('up_6000',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('up_4000',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('up_3000',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('up_2000',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('up_1000',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('up_500',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('up_250',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ul_8000',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ul_6000',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ul_4000',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ul_3000',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ul_2000',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ul_1000',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ul_500',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ul_250',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('audiogram_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
