"""Updated visit

Revision ID: 55efa92bbbdb
Revises: 88f636c23dd3
Create Date: 2024-12-26 01:58:03.217838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55efa92bbbdb'
down_revision = '88f636c23dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('whisper_test',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('nfz_info',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('nfz_info',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('whisper_test',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
