"""Added user_id to MedicalCertificate

Revision ID: 794485435350
Revises: 22e6695387f0
Create Date: 2025-01-01 19:05:38.734789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794485435350'
down_revision = '22e6695387f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_certificate', schema=None) as batch_op:
        # Dodanie kolumn
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

        # Dodanie indeksu
        batch_op.create_index('ix_medical_certificate_user_id', ['user_id'], unique=False)

        # Dodanie klucza obcego z nazwą
        batch_op.create_foreign_key(
            'fk_medical_certificate_user_id',  # Nazwa klucza obcego
            'user',  # Tabela docelowa
            ['user_id'],  # Kolumna w tabeli źródłowej
            ['id']  # Kolumna w tabeli docelowej
        )

    with op.batch_alter_table('visit', schema=None) as batch_op:
        # Dodanie kolumny
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('medical_certificate', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_medical_certificate_user_id'))
        batch_op.drop_column('is_active')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
